# Setup
name:         jharrisonau
tagline:      A site to document my experiences in solution architecture
baseurl:      ""
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
